### ISSUE TITLE
Would this work on OS X?

### ISSUE THREAD

**Issue by nojkepop** [rhasselbaum/scrappy-ddns#1]
Very interested in running this on OS X.  I am simply trying to get a notification when my public IP changes.  Any help would be greatly appreciated.  Also wondering if this can be run as a Daemon.

**Comment by rhasselbaum** [comment]
I see no reason why not. It is just a Python web app that can run inside any WSGI-compatible web server. It can also be run directly as a Python script, which is probably fine for home networks.

**Comment by nojkepop** [comment]
These are the errors I get when trying to run via terminal.

Mac-Mini:Applications User$ cd scrappy\ ddns/
Mac-Mini:scrappy ddns User$ python scrappyddns.py
Traceback (most recent call last):
  File "scrappyddns.py", line 10, in <module>
    import urllib.parse
ImportError: No module named parse
Mac-Mini:scrappy ddns User$

**Comment by rhasselbaum** [comment]
What version of Python do you have? You need at least 3.4.

**Comment by nojkepop** [comment]
I just downloaded the latest version and I am getting the same error. Sorry to bother you so much about this.

**Comment by rhasselbaum** [comment]
The [urllib.parse](https://docs.python.org/3/library/urllib.parse.html) module is a standard part of Python 3.4. I think you're still invoking Python 2. Try:

```
python --version
```

Or:

```
python3 --version
```

**Comment by nojkepop** [comment]
Here is what I get. I also tried running the app with python 3 and got a new error.

Mac-Mini:~ User$ python --version
Python 2.7.10
Mac-Mini:~ User$ python3 --version
Python 3.5.1
Mac-Mini:~ User$ cd /Applications/
Mac-Mini:Applications User$ cd scrappy\ ddns/
Mac-Mini:scrappy ddns User$ python3 scrappyddns.py
Traceback (most recent call last):
  File "scrappyddns.py", line 7, in <module>
    from flask import Flask, abort, request
ImportError: No module named 'flask'
Mac-Mini:scrappy ddns User$

**Comment by rhasselbaum** [comment]
You do not have Flask installed in a location that's accessible to the Python 3 interpreter. Sorry I do not have a Mac so I can't assist in installing that library correctly on a Mac.
